// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const CHECK_SERVER = 'CHECK_SERVER';

// Ethereum
export const SET_ADDRESS = 'SET_ADDRESS';
export const SET_NETWORK = 'SET_NETWORK';
export const SET_BALANCE = 'SET_BALANCE';
export const SET_TOKEN_BALANCE = 'SET_TOKEN_BALANCE';
export const SET_TOKEN_BALANCES = 'SET_TOKEN_BALANCES';
export const SET_WALLET = 'SET_WALLET';
export const SET_WEB3 = 'SET_WEB3';
export const SET_BLOCKEXPLORER_URL = 'SET_BLOCKEXPLORER_URL';
export const SET_CURRENT_BLOCK = 'SET_CURRENT_BLOCK';
export const SET_TRANSACTION_LOADING = 'SET_TRANSACTION_LOADING';
export const SET_TRANCHE_ALLOWANCE = 'SET_TRANCHE_ALLOWANCE';

// Summary
export const SUMMARY_SUCCESS = 'SUMMARY_SUCCESS';
export const SET_ACCRUED_REWARDS = 'SET_ACCRUED_REWARDS';
export const SET_STAKABLE_ASSETS = 'SET_STAKABLE_ASSETS';
export const SET_SLICE_STATS = 'SET_SLICE_STATS';
export const SET_TVL = 'SET_TVL';

//Loans
export const LOANS_IS_LOADING = 'LOANS_IS_LOADING';
export const LOANS_SUCCESS = 'LOANS_SUCCESS';
export const LOANS_COUNT = 'LOANS_COUNT';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const CHANGE_OWN_ALL_FILTER = 'CHANGE_OWN_ALL_FILTER';
export const CHANGE_SORTING = 'CHANGE_SORTING';
export const PAGINATION_SKIP = 'PAGINATION_SKIP';
export const PAGINATION_CURRENT = 'PAGINATION_CURRENT';

// Tranches
export const TRANCHES_IS_LOADING = 'TRANCHES_IS_LOADING';
export const TRANCHES_SUCCESS = 'TRANCHES_SUCCESS';
export const TRANCHES_COUNT = 'TRANCHES_COUNT';
export const TRANCHE_CARD_TOGGLE = 'TRANCHE_CARD_TOGGLE';
export const TRANCHE_MARKETS = 'TRANCHE_MARKETS';


// Staking
export const STAKING_IS_LOADING = 'STAKING_IS_LOADING';
export const STAKING_SUCCESS = 'STAKING_SUCCESS';
export const STAKING_COUNT = 'STAKING_COUNT';

// Earn
export const OWN_ALL_TOGGLE = 'OWN_ALL_TOGGLE';

// Path
export const CHANGE_PATH = 'CHANGE_PATH';

//theme
export const CHANGE_THEME = 'CHANGE_THEME';
